### ISSUE TITLE
Enhance modifiable variables to include explicit inputs from user

### ISSUE THREAD

**Issue by jurajsomorovsky** [RUB-NDS/ModifiableVariable#16]
See https://github.com/RUB-NDS/TLS-Attacker-Development/issues/38

**Comment by j-fliegenschmidt** [comment]
I implemented a sample solution 20f2fddf38ae21b06fa66d32e3f47fcfdade4e9e. I propose a delegate-Style solution since hard-coding the interaction would render the modification useless in a GUI-project. I am not totally clear on some of the design decisions in this project (why does it use a factory pattern? why are constructors public if you want the classes to be build through the factory?) Depending on your feedback, implementing this for all variable types should be easy. If at some point the project moves to Java source level 1.8, the dependency could be passed in lambda-style.

**Comment by j-fliegenschmidt** [comment]
#18 Implements an interactive modification for modifiable variables of type BigInteger.
